name: move-to-leetcode-dir

on:
  workflow_dispatch:
  push:
    paths:
      - '[0-9][0-9][0-9][0-9]-*/**'
      - '!leetCode/**'

jobs:
  move-files:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Move leetCode solutions
        run: |
          mkdir -p leetCode
          
          git diff --name-only HEAD^ HEAD
          
          found=0
          for d in [0-9][0-9][0-9][0-9]-*; do
            if [ -d "$d" ]; then
              echo "moving dir: $d"
              mv "$d" "leetCode/" && found=1
            fi
          done
          
          if [ $found -eq 0 ]; then
            echo "no matching dir found"
          fi
      - name: Commit & Push
        run: |
          if git status --porcelain | grep .; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "chore: move leetcode solution to leetcode dir"
            git pull --rebase origin master
            git push
          else
            echo "No change to commit"
          fi